### PR TITLE
Slow down property change submission for fast-USB platforms like Linux

### PR DESCRIPTION
**Pull request by ximion**
Hi!
This change requires the new DAQ firmware from the firmware PR https://github.com/Aharoni-Lab/Miniscope-DAQ-Cypress-firmware/pull/2 in order to work fully. As described there, Miniscopes currently don't work on Linux, because apparently Linux can send control commands to the device too quickly. Slowing things down just slightly fixes this.

I decided against an OS-specific conditional for this patch, as we don't really know whether there are some devices out there where Windows may run into the same issue as Linux does.
I really dislike this timing-related change, but I also think at least for now (and without major refactoring) this is the best we can do to make the device work everywhere.

See the code commend and the linked PR for more details.
Thanks for considering!
Cheers,
    Matthias

### CODE REVIEW

**Comment by daharoni** [comment]
Hi @ximion, I would like to merge this PR into the "dev" branch of the repo. I would like to do the same with your PR in the DAQ firmware repo. I thought I would be able to change which branch the merge would apply to myself but can't figure out how. Do you know how? If not could you make a new PR using the "dev" branch?

**Comment by ximion** [comment]
Hi! Sorry for the delay. Github slightly favours the "master is newest tested code" branch model, so I thought changing branches wasn't possible. But turns out this is actually a valid feature now, added a few years back. I think only the PR author can change the branch though (which is odd, because I allowed the project owner to make edits to the PR...).
Anyway, PR is re-targeted.

**Comment by ximion** [comment]
Hi! Sorry for the delay. Github slightly favours the "master is development focus" branch model, so I thought changing branches wasn't possible. But turns out this is actually a valid feature now, added just a few years back. I think only the PR author can change the branch though (which is odd, because I allowed the project owner to make edits to the PR...).
Anyway, PR is re-targeted :-)

**Comment by daharoni** [comment]
Thanks!

**Pull request merged**
